// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/kurnhyalcantara/koer-tax-service/protogen/account-service"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

// ListAccountRPC provides a mock function with given fields: ctx, req, opts
func (_m *MockAccountService) ListAccountRPC(ctx context.Context, req *pb.ListAccountRequest, opts ...grpc.CallOption) (*pb.ListAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountRPC")
	}

	var r0 *pb.ListAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListAccountRequest, ...grpc.CallOption) (*pb.ListAccountResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ListAccountRequest, ...grpc.CallOption) *pb.ListAccountResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ListAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAccount provides a mock function with given fields: ctx, req, opts
func (_m *MockAccountService) ValidateAccount(ctx context.Context, req *pb.ValidateAccountRequest, opts ...grpc.CallOption) (*pb.ValidateAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccount")
	}

	var r0 *pb.ValidateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) (*pb.ValidateAccountResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) *pb.ValidateAccountResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ValidateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAccountRPC provides a mock function with given fields: ctx, req, opts
func (_m *MockAccountService) ValidateAccountRPC(ctx context.Context, req *pb.ValidateAccountRequest, opts ...grpc.CallOption) (*pb.ValidateAccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccountRPC")
	}

	var r0 *pb.ValidateAccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) (*pb.ValidateAccountResponse, error)); ok {
		return rf(ctx, req, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) *pb.ValidateAccountResponse); ok {
		r0 = rf(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ValidateAccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.ValidateAccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
