// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaxRepo is an autogenerated mock type for the Tax type
type MockTaxRepo struct {
	mock.Mock
}

// SaveTaxNumber provides a mock function with given fields: ctx, companyId, taxIdNumber, taxIdName
func (_m *MockTaxRepo) SaveTaxNumber(ctx context.Context, companyId uint64, taxIdNumber string, taxIdName string) error {
	ret := _m.Called(ctx, companyId, taxIdNumber, taxIdName)

	if len(ret) == 0 {
		panic("no return value specified for SaveTaxNumber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = rf(ctx, companyId, taxIdNumber, taxIdName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTaxRepo creates a new instance of MockTaxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaxRepo {
	mock := &MockTaxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
