// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.20.3
// source: account-service/account_core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UNKNOWN_DIRECTION Direction = 0
	Direction_DESC              Direction = 1
	Direction_ASC               Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UNKNOWN_DIRECTION",
		1: "DESC",
		2: "ASC",
	}
	Direction_value = map[string]int32{
		"UNKNOWN_DIRECTION": 0,
		"DESC":              1,
		"ASC":               2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_account_service_account_core_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_account_service_account_core_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_account_service_account_core_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit      int32     `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page       int32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort       string    `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Dir        Direction `protobuf:"varint,4,opt,name=dir,proto3,enum=account.service.v1.Direction" json:"dir,omitempty"`
	TotalPages uint64    `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRows  uint64    `protobuf:"varint,6,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	Filter     string    `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_service_account_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_account_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_account_service_account_core_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *Pagination) GetDir() Direction {
	if x != nil {
		return x.Dir
	}
	return Direction_UNKNOWN_DIRECTION
}

func (x *Pagination) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetTotalRows() uint64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *Pagination) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type UserAuthority struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMaker    bool `protobuf:"varint,1,opt,name=isMaker,proto3" json:"isMaker,omitempty"`
	IsChecker  bool `protobuf:"varint,2,opt,name=isChecker,proto3" json:"isChecker,omitempty"`
	IsSigner   bool `protobuf:"varint,3,opt,name=isSigner,proto3" json:"isSigner,omitempty"`
	IsReleaser bool `protobuf:"varint,4,opt,name=isReleaser,proto3" json:"isReleaser,omitempty"`
}

func (x *UserAuthority) Reset() {
	*x = UserAuthority{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_service_account_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthority) ProtoMessage() {}

func (x *UserAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_account_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthority.ProtoReflect.Descriptor instead.
func (*UserAuthority) Descriptor() ([]byte, []int) {
	return file_account_service_account_core_proto_rawDescGZIP(), []int{1}
}

func (x *UserAuthority) GetIsMaker() bool {
	if x != nil {
		return x.IsMaker
	}
	return false
}

func (x *UserAuthority) GetIsChecker() bool {
	if x != nil {
		return x.IsChecker
	}
	return false
}

func (x *UserAuthority) GetIsSigner() bool {
	if x != nil {
		return x.IsSigner
	}
	return false
}

func (x *UserAuthority) GetIsReleaser() bool {
	if x != nil {
		return x.IsReleaser
	}
	return false
}

var File_account_service_account_core_proto protoreflect.FileDescriptor

var file_account_service_account_core_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xd3, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x83,
	0x01, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x72, 0x2a, 0x35, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x44, 0x49, 0x52,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x43, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_service_account_core_proto_rawDescOnce sync.Once
	file_account_service_account_core_proto_rawDescData = file_account_service_account_core_proto_rawDesc
)

func file_account_service_account_core_proto_rawDescGZIP() []byte {
	file_account_service_account_core_proto_rawDescOnce.Do(func() {
		file_account_service_account_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_service_account_core_proto_rawDescData)
	})
	return file_account_service_account_core_proto_rawDescData
}

var file_account_service_account_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_service_account_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_service_account_core_proto_goTypes = []interface{}{
	(Direction)(0),        // 0: account.service.v1.Direction
	(*Pagination)(nil),    // 1: account.service.v1.Pagination
	(*UserAuthority)(nil), // 2: account.service.v1.UserAuthority
}
var file_account_service_account_core_proto_depIdxs = []int32{
	0, // 0: account.service.v1.Pagination.dir:type_name -> account.service.v1.Direction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_service_account_core_proto_init() }
func file_account_service_account_core_proto_init() {
	if File_account_service_account_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_service_account_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_service_account_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuthority); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_service_account_core_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_service_account_core_proto_goTypes,
		DependencyIndexes: file_account_service_account_core_proto_depIdxs,
		EnumInfos:         file_account_service_account_core_proto_enumTypes,
		MessageInfos:      file_account_service_account_core_proto_msgTypes,
	}.Build()
	File_account_service_account_core_proto = out.File
	file_account_service_account_core_proto_rawDesc = nil
	file_account_service_account_core_proto_goTypes = nil
	file_account_service_account_core_proto_depIdxs = nil
}
