// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account-service/account_core.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Pagination) Validate() error {
	return nil
}
func (this *UserAuthority) Validate() error {
	return nil
}
