// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: koer-tax-service/koer_tax_payload.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GeneralBodyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GeneralBodyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GeneralBodyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GeneralBodyResponseMultiError, or nil if none found.
func (m *GeneralBodyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GeneralBodyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return GeneralBodyResponseMultiError(errors)
	}

	return nil
}

// GeneralBodyResponseMultiError is an error wrapping multiple validation
// errors returned by GeneralBodyResponse.ValidateAll() if the designated
// constraints aren't met.
type GeneralBodyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GeneralBodyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GeneralBodyResponseMultiError) AllErrors() []error { return m }

// GeneralBodyResponseValidationError is the validation error returned by
// GeneralBodyResponse.Validate if the designated constraints aren't met.
type GeneralBodyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GeneralBodyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GeneralBodyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GeneralBodyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GeneralBodyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GeneralBodyResponseValidationError) ErrorName() string {
	return "GeneralBodyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GeneralBodyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGeneralBodyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GeneralBodyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GeneralBodyResponseValidationError{}

// Validate checks the field values on GeneralBodyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GeneralBodyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GeneralBodyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GeneralBodyRequestMultiError, or nil if none found.
func (m *GeneralBodyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GeneralBodyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProcessId

	// no validation rules for Token

	if len(errors) > 0 {
		return GeneralBodyRequestMultiError(errors)
	}

	return nil
}

// GeneralBodyRequestMultiError is an error wrapping multiple validation errors
// returned by GeneralBodyRequest.ValidateAll() if the designated constraints
// aren't met.
type GeneralBodyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GeneralBodyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GeneralBodyRequestMultiError) AllErrors() []error { return m }

// GeneralBodyRequestValidationError is the validation error returned by
// GeneralBodyRequest.Validate if the designated constraints aren't met.
type GeneralBodyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GeneralBodyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GeneralBodyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GeneralBodyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GeneralBodyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GeneralBodyRequestValidationError) ErrorName() string {
	return "GeneralBodyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GeneralBodyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGeneralBodyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GeneralBodyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GeneralBodyRequestValidationError{}

// Validate checks the field values on V3SaveTaxNumberRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *V3SaveTaxNumberRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on V3SaveTaxNumberRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// V3SaveTaxNumberRequestMultiError, or nil if none found.
func (m *V3SaveTaxNumberRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *V3SaveTaxNumberRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaxIdNumber

	// no validation rules for TaxOwnerName

	if len(errors) > 0 {
		return V3SaveTaxNumberRequestMultiError(errors)
	}

	return nil
}

// V3SaveTaxNumberRequestMultiError is an error wrapping multiple validation
// errors returned by V3SaveTaxNumberRequest.ValidateAll() if the designated
// constraints aren't met.
type V3SaveTaxNumberRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m V3SaveTaxNumberRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m V3SaveTaxNumberRequestMultiError) AllErrors() []error { return m }

// V3SaveTaxNumberRequestValidationError is the validation error returned by
// V3SaveTaxNumberRequest.Validate if the designated constraints aren't met.
type V3SaveTaxNumberRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e V3SaveTaxNumberRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e V3SaveTaxNumberRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e V3SaveTaxNumberRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e V3SaveTaxNumberRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e V3SaveTaxNumberRequestValidationError) ErrorName() string {
	return "V3SaveTaxNumberRequestValidationError"
}

// Error satisfies the builtin error interface
func (e V3SaveTaxNumberRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sV3SaveTaxNumberRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = V3SaveTaxNumberRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = V3SaveTaxNumberRequestValidationError{}
