// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: koer-tax-service/koer_tax_api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KoerTaxService_V3SaveTaxNumber_FullMethodName = "/koer_tax.service.v3.KoerTaxService/V3SaveTaxNumber"
)

// KoerTaxServiceClient is the client API for KoerTaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Generated according to https://cloud.google.com/apis/design/standard_methods
type KoerTaxServiceClient interface {
	V3SaveTaxNumber(ctx context.Context, in *V3SaveTaxNumberRequest, opts ...grpc.CallOption) (*GeneralBodyResponse, error)
}

type koerTaxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKoerTaxServiceClient(cc grpc.ClientConnInterface) KoerTaxServiceClient {
	return &koerTaxServiceClient{cc}
}

func (c *koerTaxServiceClient) V3SaveTaxNumber(ctx context.Context, in *V3SaveTaxNumberRequest, opts ...grpc.CallOption) (*GeneralBodyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralBodyResponse)
	err := c.cc.Invoke(ctx, KoerTaxService_V3SaveTaxNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KoerTaxServiceServer is the server API for KoerTaxService service.
// All implementations must embed UnimplementedKoerTaxServiceServer
// for forward compatibility.
//
// Generated according to https://cloud.google.com/apis/design/standard_methods
type KoerTaxServiceServer interface {
	V3SaveTaxNumber(context.Context, *V3SaveTaxNumberRequest) (*GeneralBodyResponse, error)
	mustEmbedUnimplementedKoerTaxServiceServer()
}

// UnimplementedKoerTaxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKoerTaxServiceServer struct{}

func (UnimplementedKoerTaxServiceServer) V3SaveTaxNumber(context.Context, *V3SaveTaxNumberRequest) (*GeneralBodyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method V3SaveTaxNumber not implemented")
}
func (UnimplementedKoerTaxServiceServer) mustEmbedUnimplementedKoerTaxServiceServer() {}
func (UnimplementedKoerTaxServiceServer) testEmbeddedByValue()                        {}

// UnsafeKoerTaxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KoerTaxServiceServer will
// result in compilation errors.
type UnsafeKoerTaxServiceServer interface {
	mustEmbedUnimplementedKoerTaxServiceServer()
}

func RegisterKoerTaxServiceServer(s grpc.ServiceRegistrar, srv KoerTaxServiceServer) {
	// If the following call pancis, it indicates UnimplementedKoerTaxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KoerTaxService_ServiceDesc, srv)
}

func _KoerTaxService_V3SaveTaxNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(V3SaveTaxNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoerTaxServiceServer).V3SaveTaxNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KoerTaxService_V3SaveTaxNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoerTaxServiceServer).V3SaveTaxNumber(ctx, req.(*V3SaveTaxNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KoerTaxService_ServiceDesc is the grpc.ServiceDesc for KoerTaxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KoerTaxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koer_tax.service.v3.KoerTaxService",
	HandlerType: (*KoerTaxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "V3SaveTaxNumber",
			Handler:    _KoerTaxService_V3SaveTaxNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "koer-tax-service/koer_tax_api.proto",
}
