// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: registration-online-service/registration_online_api.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_RegistrationOnlineService_InsertNewRegol_0(ctx context.Context, marshaler runtime.Marshaler, client RegistrationOnlineServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GeneralBodyRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.InsertNewRegol(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_RegistrationOnlineService_InsertNewRegol_0(ctx context.Context, marshaler runtime.Marshaler, server RegistrationOnlineServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GeneralBodyRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.InsertNewRegol(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterRegistrationOnlineServiceHandlerServer registers the http handlers for service RegistrationOnlineService to "mux".
// UnaryRPC     :call RegistrationOnlineServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterRegistrationOnlineServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterRegistrationOnlineServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server RegistrationOnlineServiceServer) error {

	mux.Handle("POST", pattern_RegistrationOnlineService_InsertNewRegol_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/registration_online.service.v1.RegistrationOnlineService/InsertNewRegol", runtime.WithHTTPPathPattern("/api/registration-online/insert"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_RegistrationOnlineService_InsertNewRegol_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RegistrationOnlineService_InsertNewRegol_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterRegistrationOnlineServiceHandlerFromEndpoint is same as RegisterRegistrationOnlineServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterRegistrationOnlineServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterRegistrationOnlineServiceHandler(ctx, mux, conn)
}

// RegisterRegistrationOnlineServiceHandler registers the http handlers for service RegistrationOnlineService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterRegistrationOnlineServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterRegistrationOnlineServiceHandlerClient(ctx, mux, NewRegistrationOnlineServiceClient(conn))
}

// RegisterRegistrationOnlineServiceHandlerClient registers the http handlers for service RegistrationOnlineService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "RegistrationOnlineServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "RegistrationOnlineServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "RegistrationOnlineServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterRegistrationOnlineServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client RegistrationOnlineServiceClient) error {

	mux.Handle("POST", pattern_RegistrationOnlineService_InsertNewRegol_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/registration_online.service.v1.RegistrationOnlineService/InsertNewRegol", runtime.WithHTTPPathPattern("/api/registration-online/insert"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_RegistrationOnlineService_InsertNewRegol_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RegistrationOnlineService_InsertNewRegol_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_RegistrationOnlineService_InsertNewRegol_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "registration-online", "insert"}, ""))
)

var (
	forward_RegistrationOnlineService_InsertNewRegol_0 = runtime.ForwardResponseMessage
)
